[build]
builder = "nixpacks"
buildCommand = "npm run build"
postBuildCommand = "npx prisma generate"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build.env]
PRISMA_GENERATE_DATAPROXY = "false"

